---
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        language_version: python3.12
        files: src
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        language_version: python3.12
        files: src
      - id: ruff-format
        args: [ --check ]
        files: src
